spring.application.name=user-gateway

# Spring Boot REST server
server.port=8080

# gRPC client config
grpc.client.user-service.address=static://localhost:9090
grpc.client.user-service.negotiationType=plaintext

# Optional: timeout settings (recommended)
grpc.client.user-service.enableKeepAlive=true
grpc.client.user-service.keepAliveWithoutCalls=true
grpc.client.user-service.keepAliveTime=30s
grpc.client.user-service.keepAliveTimeout=10s