spring.application.name=user-service

# Spring Boot HTTP server (optional, not really used here)
server.port=8081

# gRPC server port
grpc.server.port=9090

# Optional: graceful shutdown
grpc.server.shutdownGrace=30s

# Optional: enable reflection (useful for debugging via grpcurl/BloomRPC)
grpc.server.enableReflection=true